spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security_authority?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&useSSL=false
    username: root
    password: 123456
  #允许我们自己覆盖spring中的配置不然会出现两个ID一样的bean
  main:
    allow-bean-definition-overriding: true
mybatis:
  #  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.henu.oauth.domain
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

server:
  port: 9902

logging:
  level:
    com.henu.oauth: debug